=== e-VRO/frvcpy/instances/frvcpy-instance.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "FRVCP Instance",
    "description": "Instance suitable for use with frvcpy",
    "type": "object",
    "properties": {
        "max_q": {
            "description": "The vehicle's battery capacity",
            "type": "number"
        },
        "t_max": {
            "description": "Maximum duration (time) of the vehicle's route",
            "type": "number"
        },
        "css": {
            "description": "Charging station information: node IDs and types (speed or technology)",
            "type": "array",
            "items": {
                "$ref": "#/definitions/cs_info"
            }
        },
        "process_times": {
            "description": "Time required for the vehicle to process (stay at) each node",
            "type": "array",
            "items": {
                "type": "number"
            }
        },
        "time_matrix": {
            "description": "Time required for the vehicle to travel between nodes",
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "number"
                }
            }
        },
        "energy_matrix": {
            "description": "Energy required for the vehicle to travel between nodes",
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "number"
                }
            }
        },
        "breakpoints_by_type": {
            "description": "Breakpoints defining the charging function for each CS type present in the \"css\" array",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "cs_type": {
                        "type": "integer"
                    },
                    "time": {
                        "description": "Array of breakpoints' time coordinates",
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    },
                    "charge": {
                        "description": "Array of breakpoints' charge coordinates",
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    }
                }
            }
        }
    },
    "required": [
        "max_q",
        "css",
        "breakpoints_by_type",
        "energy_matrix",
        "time_matrix"
    ],
    "definitions": {
        "cs_info": {
            "title": "CS Node Info",
            "description": "Node ID and type (speed/technology) of the CS node",
            "type": "object",
            "properties": {
                "node_id": {
                    "type": "integer"
                },
                "cs_type": {
                    "type": "integer"
                }
            },
            "required": [
                "node_id",
                "cs_type"
            ]
        }
    }
}

=== e-VRO/frvcpy/frvcpy/test/data/frvcpy-instance.json
{
    "max_q": 16000.0,
    "t_max": 10.0,
    "css": [
        {
            "node_id": 41,
            "cs_type": 2
        },
        {
            "node_id": 42,
            "cs_type": 1
        },
        {
            "node_id": 43,
            "cs_type": 0
        },
        {
            "node_id": 44,
            "cs_type": 2
        },
        {
            "node_id": 45,
            "cs_type": 2
        },
        {
            "node_id": 46,
            "cs_type": 2
        },
        {
            "node_id": 47,
            "cs_type": 0
        },
        {
            "node_id": 48,
            "cs_type": 1
        },
        {
            "node_id": 49,
            "cs_type": 0
        }
    ],
    "process_times": [
        0,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "breakpoints_by_type": [
        {
            "cs_type": 0,
            "time": [
                0.0,
                0.31,
                0.39,
                0.51
            ],
            "charge": [
                0.0,
                13600.0,
                15200.0,
                16000.0
            ]
        },
        {
            "cs_type": 1,
            "time": [
                0.0,
                0.62,
                0.77,
                1.01
            ],
            "charge": [
                0.0,
                13600.0,
                15200.0,
                16000.0
            ]
        },
        {
            "cs_type": 2,
            "time": [
                0.0,
                1.26,
                1.54,
                2.04
            ],
            "charge": [
                0.0,
                13600.0,
                15200.0,
                16000.0
            ]
        }
    ],
    "energy_matrix": [
        [
            0.0,
            4980.433747426021,
            10361.014142568283,
            6637.439736072937,
            7292.472681642351,
            9849.375932007062,
            4157.790316081368,
            8191.912551413132,
            4418.216905607962,
            5811.613507667213,
            5992.456846945165,
            4059.5046649806923,
            7682.287765535732,
            8269.890038567622,
            5903.175522547166,
            6292.411724648985,
            5243.285736301236,
            3638.2932983749392,
            4115.891838350469,
            8718.82598533197,
            9419.279513980886,
            9681.28389277476,
            9853.43729682693,
            5454.517623035056,
            7322.77888680247,
            3499.5178239294632,
            8555.215971119607,
            5749.055628970728,
            4755.4713554494265,
            6202.09704958734,
            4672.224610664603,
            8281.90959637329,
            6965.628561012997,
            7575.068584673012,
            8124.976923044152,
            6324.298997715082,
            6969.408264874428,
            7047.032731050707,
            5707.308089195815,
            5018.765566601014,
            5249.89181436151,
            7278.649642962629,
            6615.5145538725865,
            8772.746594567745,
            3795.6160978818702,
            9174.16796295446,
            2975.3088075021733,
            1881.530709953999,
            6435.881107121229,
            0.0
        ],
        [
            4980.433747426021,
            0.0,
            15161.792543264795,
            11543.805495264547,
            11839.967535850761,
            14721.159569222118,
            7130.553975673979,
            8913.654991780868,
            7727.809460804529,
            6118.128032740079,
            10497.528578194011,
            7133.114348760995,
            12630.187300669773,
            12082.268839605415,
            2271.4164771129053,
            6237.764272958702,
            10066.571070876118,
            5307.733302691459,
            3036.18927481473,
            11916.861609710839,
            13222.722511835449,
            14053.829771631647,
            13816.313953077355,
            7524.246743860809,
            2543.4760294722664,
            1547.0521363224955,
            12148.633668030327,
            3485.1508665336137,
            2358.141482184646,
            7792.18879712241,
            9619.26208838287,
            9169.287220116948,
            2018.2963886654504,
            12174.358812684959,
            12356.110140837205,
            11214.367598085948,
            9809.428659458204,
            7811.76196513949,
            10260.127999323398,
            4258.892535037718,
            10165.201055562058,
            11207.126987435271,
            5652.661430689088,
            11865.650134948359,
            8508.3864877543,
            11117.29508468674,
            3050.196971098751,
            6187.158071360388,
            10172.86103131759,
            4980.433747426021
        ],
        [
            10361.014142568283,
            15161.792543264795,
            0.0,
            5878.473042593629,
            3592.8857656485548,
            879.2619419149223,
            11596.204255056911,
            12044.111956159326,
            11141.14537704719,
            14792.872650367812,
            8252.911796753919,
            8868.536114404676,
            3124.6424795486596,
            10679.95471959034,
            16257.90370289171,
            12603.785393682329,
            5120.75800053078,
            10803.047096190037,
            14319.851441704972,
            12384.386339257993,
            11081.427311046173,
            2913.374868601705,
            4672.920994945239,
            13014.002374846103,
            17626.82619085183,
            13797.280585771241,
            11366.805977274355,
            15922.28101788497,
            15074.898113254363,
            10466.97738724031,
            6627.992248788466,
            11809.80313129732,
            17012.350155475284,
            3199.6176529391755,
            9296.932373772544,
            6155.138605263086,
            12440.43106166342,
            11722.067463762525,
            5009.382602926233,
            13019.887912343946,
            5165.575052692585,
            5448.295174868924,
            13660.221562075776,
            7425.308916132715,
            8277.446768176767,
            10117.882838074376,
            12364.453397239198,
            10096.89138423307,
            6362.164161077581,
            10361.014142568283
        ],
        [
            6637.439736072937,
            11543.805495264547,
            5878.473042593629,
            0.0,
            5273.430601847339,
            5038.40872696926,
            6145.8071327125135,
            12315.016240346578,
            5581.907436083116,
            9435.547562939842,
            2379.2360249668377,
            7741.128188126069,
            2860.399065252959,
            4984.969909638372,
            11957.342932273874,
            11576.254319187188,
            3648.1350115504224,
            8979.023645419362,
            9782.255778960189,
            6598.761839352896,
            5636.123030284204,
            7207.625844374832,
            8522.677194549844,
            7400.010557424901,
            13692.71624349968,
            10008.353073807899,
            5653.949532185443,
            11226.75000278353,
            10692.026015330302,
            10220.22114792532,
            1995.1131703489907,
            12225.621980598778,
            13555.992217466042,
            5170.9478398548945,
            3746.315690114756,
            357.31857284501757,
            6572.4297495294695,
            11486.766094619494,
            4868.06076636272,
            11055.11992528801,
            2998.374820215111,
            7169.452777234815,
            12323.9155836325,
            9692.058685465126,
            3150.0607633028294,
            11680.961339397541,
            9466.571779160606,
            5468.496851283722,
            7269.122410924168,
            6637.439736072937
        ],
        [
            7292.472681642351,
            11839.967535850761,
            3592.8857656485548,
            5273.430601847339,
            0.0,
            3518.8068379068495,
            9492.472346549132,
            8655.68138926682,
            9196.798780689942,
            12418.706278232044,
            7231.3285432208095,
            5283.921513658203,
            2970.206221796728,
            10159.569149944302,
            13155.154229901678,
            9023.744545641792,
            2365.9069349828605,
            7240.17707397409,
            11391.958855372503,
            11635.270328832072,
            10896.770880632483,
            2456.928977402482,
            3312.387733946617,
            11018.724475296585,
            14354.40181834478,
            10568.9383484104,
            10798.292978522115,
            13024.243560088242,
            12043.492018513565,
            6940.088255922975,
            4826.933874106831,
            8453.657677301582,
            13611.948622901129,
            397.27981322991997,
            9006.462697002637,
            5362.495046617759,
            11076.270384249385,
            8221.301980221866,
            1594.18327443867,
            9442.945945254583,
            2825.726676449794,
            2234.082935456963,
            10070.853985635975,
            4698.844605325867,
